CREATE DATABASE IF NOT EXISTS RestaurantDB;

USE RestaurantDB;

CREATE TABLE IF NOT EXISTS ROLES
(
    ROLE_ID         INT NOT NULL,
    ROLE_NAME       VARCHAR(14),
    PRIMARY KEY (ROLE_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID         INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME      VARCHAR(14),
    LAST_NAME       VARCHAR(14),
    EMAIL           VARCHAR(50) NOT NULL UNIQUE,
    USERNAME        VARCHAR(14),
    PASSWORD        VARCHAR(14),
    ROLE_ID         INT,
    IS_ACTIVE       BOOLEAN,
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)

) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ADDRESSES
(
    ADDRESS_ID      INT NOT NULL,
    USER_ID         INT,
    STREET          VARCHAR(20),
    HOUSE           VARCHAR(5),
    APARTMENT       VARCHAR(5),
    PRIMARY KEY (ADDRESS_ID),
    CONSTRAINT FK_ADDRESS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
) ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS ORDERS
(
    ORDER_ID        INT NOT NULL,
    CUSTOMER_ID     INT,
    ORDER_DATETIME  DATETIME,
    ORDER_STATUS    VARCHAR(14),
    DELIVERY_ADDRESS_ID INT,
    PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_ORDER_ADDRESS FOREIGN KEY (DELIVERY_ADDRESS_ID) REFERENCES ADDRESSES (ADDRESS_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DISHES
(
    DISH_ID         INT NOT NULL,
    DISH_NAME       VARCHAR(14),
    DESCRIPTION     VARCHAR(200),
    PRICE           DECIMAL,
    IS_AVAILABLE    BOOLEAN,
    PRIMARY KEY (DISH_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ORDER_ITEMS
(
    ORDER_ITEM_ID   INT NOT NULL,
    ORDER_ID        INT NOT NULL,
    DISH_ID         INT NOT NULL,
    DISH_PRICE      DECIMAL,
    QUANTITY        INT NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID),
    FOREIGN KEY (DISH_ID) REFERENCES DISHES (DISH_ID)
) ENGINE=InnoDB;





COMMIT;